sendgrid:
  api-key: ${SENDGRID_API_KEY}
spring:
  application:
    name: CodeByZ
  datasource:
    driver-class-name: org.postgresql.Driver
    #    url: jdbc:postgresql://127.0.0.1:5432/newdb
    url: jdbc:postgresql://127.0.0.1:5432/codebyzplatform
    username: postgres
    password: 122333

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
        format_sql: true
        show_sql: true

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  #https://online-course-tg-bot-for-users-up37-5p5csufu1.vercel.app/auth/telegram?chatId=123456789
  #  mail:
  #    host: smtp.gmail.com
  #    port: 587
  #    username: codebyzplatform@gmail.com
  #    password: yfof ldkg jmqh jjqr
  #    properties:
  #      mail:
  #        smtp:
  #          auth: true
  #          starttls:
  #            enable: true


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "${BACKEND_URL}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

server:
  port: 8094
  forward-headers-strategy: framework

jwt:
  secret: ${JWT_SECRET}
  expiration:
    ms: 3600000000000
  refresh:
    expiration:
      ms: 3600000000000

verified:
  email:
    time:
      milli:
        second: 120000

logging:
  level:
    org.springframework.security: DEBUG
    uz.codebyz.onlinecoursebackend: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

frontend:
  base-url: ${FRONTEND}

user:
  profile:
    images: uploads/user-profile-images
course:
  image:
    url: uploads/course-promo-images/
  video:
    url: uploads/course-promo-videos/
    lesson:
      url: uploads/lesson-videos/
  homework:
    file:
      upload: uploads/homework-files/
  certificateFolder: uploads/certificates/
  skill:
    icon: uploads/skills/

google:
  gemini:
    api-key: ${GEMINI_API_KEY}
    model: ${GEMINI_MODEL}
telegram:
  base-url: https://codebyz.online
  users:
    bot:
      token: 8548536952:AAGt23Cm16-rD0ueJoR7kQVerRm0Wfwbxec
      username: https://t.me/CodeByz_Patform_Bot
      webhook-path: /telegram/users/webhook
  teachers:
    bot:
      token: 8072174037:AAFtxX3zla14leblkeSzSONtx96f25Vu8Ec
      username: https://t.me/CodeByZ_Teachers_Bot
      webhook-path: /telegram/teachers/webhook
  bot:
    token: 7714880768:AAGwc6dHpqMwyJ7pBqP_mungB5-27YC5i2Q
    username: https://t.me/CodeByZ_Notification_Bot
admins:
  chat:
    ids:
      - 1660155052
      - 7882316826

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  server-url: ${BACKEND_URL}

swagger:
  title: "CodeByZ Online Course API"
  description: "Auth, Users, Courses va boshqaruv uchun API"
  version: "v1"



payments:
  payme:
    merchant-id: PAYME_MERCHANT_ID
    secret-key: PAYME_SECRET_KEY
    test-mode: PAYME_TEST_MODE
  click:
    merchant-id: CLICK_MERCHANT_ID
    service-id: CLICK_SERVICE_ID
    secret-key: CLICK_SECRET_KEY
  uzum:
    merchant-id: UZUM_MERCHANT_ID
    secret-key: UZUM_SECRET_KEY
    api-url: UZUM_API_URL
  paylov:
    merchant-id: PAYLOV_MERCHANT_ID
    secret-key: PAYLOV_SECRET_KEY
    api-url: PAYLOV_API_URL
  hamkor:
    terminal-id: HAMKOR_TERMINAL_ID
    secret-key: HAMKOR_SECRET_KEY
    api-url: HAMKOR_API_URL
  paypal:
    client-id: PAYPAL_CLIENT_ID
    client-secret: PAYPAL_CLIENT_SECRET
    mode: PAYPAL_MODE
    api-url: PAYPAL_API_URL


location:
  api: https://ipwho.is/


login:
  security:
    max-wrong-attempts: 3
  device:
    count: 3

admin:
  email: ziyatovzafar98@gmail.com
  password: Zafar123$
  username: admin
auth-frontend:
  login-url: https://online-course-tg-bot-for-users-scew.vercel.app
#  login-url: https://online-course-tg-bot-for-users-9u8c.vercel.app

courses:
  list:
    size: 10
